### ISSUE TITLE
Question regarding pinephone hardware

### ISSUE THREAD

**Issue by M-I** [edison-moreland/hudOS#1]
Hi, I just stumble upon your project, would love to test hudOS when it's in an usable state.

Maybe you can help me.  I just acquired a pinephone (second-hand)  to use with with my nreal air. Can you you tell me which OS/version you used to test the glasses?  I'm having difficulties determinig if the model I have needs the hardware mod or not:

 - The phone detects the glasses (I can set extended or mirroring, set which display is primary), but nothing appears on the glasses. I can see "nreal air" in 'dmesg'.

- If I plug a USB dock with HDMI, I can use my phone with an external monitor, mouse and keyboard. 

From my readings, it seemed like it was more of a "either it works, or not at all" situation, but maybe I'm not on the right distro, or the right kernel ?  (uname -a > Linux mobian 6.1-sunxi64)

Sorry to disturb you with my issue. The combo Pinephone X Nreal Air is quite uncommon.

**Comment by superb-eddie** [comment]
If the usb dock works then the glasses should work in theory, but I should note that I have not gotten anything to display on the glasses yet.

**Comment by superb-eddie** [comment]
@M-I Just an FYI, the Nreal glasses do work with the pinephone pro. The pro is still a very new device so you might run into more issues but it's working great for me so far
